#!/bin/bash
# Generated by Copilot
# Script for building and deploying the Cocktail Finder app to GitHub Pages

REPO_URL="https://github.com/xlabsinc/cocktails"
PAGES_URL="https://xlabsinc.github.io/cocktails"

echo "🍸 Building and deploying Cocktail Finder app..."
echo "📂 Repository: $REPO_URL"
echo "🌐 Deployment URL: $PAGES_URL"

# Install dependencies if node_modules doesn't exist
if [ ! -d "node_modules" ]; then
  echo "📦 Installing dependencies..."
  npm install
fi

# Build the app
echo "🏗️ Building the app..."
npm run build

# Deploy to GitHub Pages
echo "🚀 Deploying to GitHub Pages..."
npm run deploy

echo "✅ Deployment complete! Your app should be live soon at:"
echo "   $PAGES_URL"