// Generated by Copilot
export interface Cocktail {
  name: string;
  ingredients: string[];
  garnish?: string;
  recipe?: string;
  glass?: string;
  image?: string;
}

export interface CocktailSource {
  url: string;
  isDefault: boolean;
}

export interface SelectedIngredients {
  [key: string]: boolean;
}