// Generated by Copilot
import React from 'react';
import { Cocktail } from '../../types/cocktail';
import { CocktailCard as StyledCocktailCard, CloseButton } from '../ui/StyledComponents';

interface CocktailCardProps {
  cocktail: Cocktail;
  onClose?: () => void;
  showCloseButton?: boolean;
}

const CocktailCard: React.FC<CocktailCardProps> = ({ 
  cocktail, 
  onClose,
  showCloseButton = true
}) => {
  const { name, ingredients, preparation, glass, garnish } = cocktail;

  return (
    <StyledCocktailCard>
      {showCloseButton && onClose && (
        <CloseButton onClick={onClose} aria-label="Close">
          ✕
        </CloseButton>
      )}
      
      <h3 style={{ marginTop: 0 }}>{name}</h3>
      
      <div style={{ marginBottom: '16px' }}>
        <p style={{ fontWeight: 'bold', marginBottom: '4px' }}>Ingredients:</p>
        <ul style={{ paddingLeft: '20px', margin: '0' }}>
          {ingredients.map((ingredient, index) => (
            <li key={index}>{ingredient}</li>
          ))}
        </ul>
      </div>
      
      {glass && (
        <div style={{ marginBottom: '16px' }}>
          <p style={{ fontWeight: 'bold', marginBottom: '4px' }}>Glass:</p>
          <p style={{ margin: 0 }}>{glass}</p>
        </div>
      )}
      
      {garnish && (
        <div style={{ marginBottom: '16px' }}>
          <p style={{ fontWeight: 'bold', marginBottom: '4px' }}>Garnish:</p>
          <p style={{ margin: 0 }}>{garnish}</p>
        </div>
      )}
      
      {preparation && (
        <div style={{ marginBottom: '8px' }}>
          <p style={{ fontWeight: 'bold', marginBottom: '4px' }}>Preparation:</p>
          <p style={{ margin: 0 }}>{preparation}</p>
        </div>
      )}
    </StyledCocktailCard>
  );
};

export default CocktailCard;