// Generated by Copilot
import React, { useState } from 'react';
import { Cocktail } from '../../types/cocktail';
import { CocktailCard as StyledCocktailCard, CloseButton } from '../ui/StyledComponents';

interface CocktailCardProps {
  cocktail: Cocktail;
  onClose?: () => void;
  showCloseButton?: boolean;
}

const CocktailCard: React.FC<CocktailCardProps> = ({ 
  cocktail, 
  onClose,
  showCloseButton = true
}) => {
  const { name, ingredients, recipe, glass, garnish } = cocktail;
  const [_showIngredients, _setShowIngredients] = useState<boolean>(false);
  const [_showRecipe, _setShowRecipe] = useState<boolean>(false);

  const _toggleIngredients = () => {
    _setShowIngredients(prev => !prev);
  };

  const _toggleRecipe = () => {
    _setShowRecipe(prev => !prev);
  };

  return (
    <StyledCocktailCard>
      {showCloseButton && onClose && (
        <CloseButton onClick={onClose} aria-label="Close">
          ✕
        </CloseButton>
      )}
      
      <h3 style={{ marginTop: 0 }}>{name}</h3>
      
      <div style={{ marginBottom: '16px' }}>
        <div 
          style={{ 
            fontWeight: 'bold', 
            marginBottom: '4px',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            cursor: 'pointer',
            padding: '4px 8px',
            backgroundColor: '#f5f5f7',
            borderRadius: '4px'
          }}
          onClick={_toggleIngredients}
        >
          <span>Ingredients:</span>
          <span style={{ fontSize: '12px' }}>
            {_showIngredients ? '▼' : '►'}
          </span>
        </div>
        
        {_showIngredients && (
          <ul style={{ paddingLeft: '20px', margin: '8px 0 0' }}>
            {ingredients.map((ingredient, index) => (
              <li key={index}>{ingredient}</li>
            ))}
          </ul>
        )}
      </div>
      
      {recipe && (
        <div style={{ marginBottom: '16px' }}>
          <div 
            style={{ 
              fontWeight: 'bold', 
              marginBottom: '4px',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              cursor: 'pointer',
              padding: '4px 8px',
              backgroundColor: '#f5f5f7',
              borderRadius: '4px'
            }}
            onClick={_toggleRecipe}
          >
            <span>Recipe:</span>
            <span style={{ fontSize: '12px' }}>
              {_showRecipe ? '▼' : '►'}
            </span>
          </div>
          
          {_showRecipe && (
            <p style={{ margin: '8px 0 0', padding: '0 4px' }}>
              {recipe}
            </p>
          )}
        </div>
      )}
      
      {glass && (
        <div style={{ marginBottom: '16px' }}>
          <p style={{ fontWeight: 'bold', marginBottom: '4px' }}>Glass:</p>
          <p style={{ margin: 0 }}>{glass}</p>
        </div>
      )}
      
      {garnish && (
        <div style={{ marginBottom: '16px' }}>
          <p style={{ fontWeight: 'bold', marginBottom: '4px' }}>Garnish:</p>
          <p style={{ margin: 0 }}>{garnish}</p>
        </div>
      )}
    </StyledCocktailCard>
  );
};

export default CocktailCard;