// Generated by Copilot
import styled from 'styled-components';

export const AppContainer = styled.div`
  max-width: 1200px;
  margin: 0 auto;
  padding: 20px;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
`;

export const Header = styled.header`
  text-align: center;
  margin-bottom: 40px;
`;

export const Title = styled.h1`
  font-size: 2.5rem;
  color: #1d1d1f;
  font-weight: 700;
`;

export const Subtitle = styled.h2`
  font-size: 1.5rem;
  color: #86868b;
  font-weight: 400;
`;

export const Card = styled.div`
  background: #fff;
  border-radius: 14px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.08);
  padding: 24px;
  margin-bottom: 20px;
  transition: transform 0.3s ease, box-shadow 0.3s ease;
  
  &:hover {
    transform: translateY(-4px);
    box-shadow: 0 6px 25px rgba(0, 0, 0, 0.1);
  }
`;

export const CocktailCard = styled(Card)`
  position: relative;
  display: flex;
  flex-direction: column;
  height: 100%;
`;

export const CloseButton = styled.button`
  position: absolute;
  top: 12px;
  right: 12px;
  background: transparent;
  border: none;
  border-radius: 50%;
  width: 30px;
  height: 30px;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  opacity: 0.7;
  transition: opacity 0.2s ease, background-color 0.2s ease;
  font-size: 18px;
  
  &:hover {
    opacity: 1;
    background-color: rgba(0, 0, 0, 0.05);
  }
`;

export const Grid = styled.div`
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 24px;
  margin-top: 24px;
`;

export const Button = styled.button`
  background-color: #0071e3;
  color: white;
  border: none;
  border-radius: 8px;
  padding: 12px 20px;
  font-size: 16px;
  font-weight: 500;
  cursor: pointer;
  transition: background-color 0.2s ease;
  
  &:hover {
    background-color: #0077ed;
  }
  
  &:active {
    background-color: #0068d1;
  }
  
  &:disabled {
    background-color: #b0b0b0;
    cursor: not-allowed;
  }
`;

export const SecondaryButton = styled(Button)`
  background-color: #eaeaea;
  color: #1d1d1f;
  
  &:hover {
    background-color: #d6d6d6;
  }
  
  &:active {
    background-color: #c4c4c4;
  }
`;

export const SearchInput = styled.input`
  width: 100%;
  padding: 14px 16px;
  font-size: 16px;
  border: none;
  border-radius: 10px;
  background-color: #f5f5f7;
  margin-bottom: 20px;
  transition: background-color 0.2s ease;
  
  &:focus {
    background-color: #ffffff;
    outline: none;
    box-shadow: 0 0 0 2px #0071e3;
  }
`;

export const TextField = styled.input`
  width: 100%;
  padding: 14px 16px;
  font-size: 16px;
  border: 1px solid #d2d2d7;
  border-radius: 10px;
  transition: border-color 0.2s ease;
  
  &:focus {
    border-color: #0071e3;
    outline: none;
    box-shadow: 0 0 0 2px rgba(0, 113, 227, 0.2);
  }
`;

export const ButtonGroup = styled.div`
  display: flex;
  gap: 10px;
  margin: 20px 0;
`;

export const IngredientTag = styled.span<{ active?: boolean }>`
  display: inline-block;
  background-color: ${props => props.active ? "#0071e3" : "#f5f5f7"};
  color: ${props => props.active ? "#ffffff" : "#1d1d1f"};
  padding: 8px 14px;
  margin: 0 6px 6px 0;
  border-radius: 20px;
  cursor: pointer;
  transition: all 0.2s ease;
  
  &:hover {
    background-color: ${props => props.active ? "#0077ed" : "#d6d6d6"};
  }
`;

export const Divider = styled.hr`
  border: none;
  height: 1px;
  background-color: #d2d2d7;
  margin: 24px 0;
`;

export const Section = styled.section`
  margin-bottom: 32px;
`;

export const Loading = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 40px;
  font-size: 18px;
  color: #86868b;
`;

export const ErrorMessage = styled.div`
  background-color: #fff1f0;
  border: 1px solid #ffa39e;
  color: #cf1322;
  padding: 12px 16px;
  border-radius: 8px;
  margin-bottom: 20px;
`;

export const ModalBackdrop = styled.div`
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.4);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
`;

export const Modal = styled.div`
  background-color: white;
  border-radius: 14px;
  padding: 24px;
  width: 100%;
  max-width: 500px;
  box-shadow: 0 4px 30px rgba(0, 0, 0, 0.2);
`;

export const ModalHeader = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
`;

export const ModalTitle = styled.h3`
  font-size: 1.4rem;
  font-weight: 600;
  color: #1d1d1f;
  margin: 0;
`;

export const DropdownContainer = styled.div`
  position: relative;
  width: 100%;
`;

export const DropdownMenu = styled.ul`
  position: absolute;
  top: 100%;
  left: 0;
  width: 100%;
  background-color: white;
  border-radius: 10px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.15);
  max-height: 300px;
  overflow-y: auto;
  z-index: 10;
  padding: 8px 0;
  margin-top: 4px;
  list-style-type: none;
`;

export const DropdownItem = styled.li`
  padding: 12px 16px;
  cursor: pointer;
  transition: background-color 0.2s ease;
  
  &:hover {
    background-color: #f5f5f7;
  }
`;